name: main
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: bahmutov/npm-install@v1
      - run: yarn build
      - run: yarn lint
      - run: yarn test
